# __________ __                           __________                __   __        __                            ________
# \______   \  | _____  ___ __  __________\______   \_____ ________/  |_|__| ____ |  |   ____   ______   ___  __/  _____/
#  |     ___/  | \__  \<   |  |/ __ \_  __ \     ___/\__  \\_  __ \   __\  |/ ___\|  | _/ __ \ /  ___/   \  \/ /   __  \ 
#  |    |   |  |__/ __ \\___  \  ___/|  | \/    |     / __ \|  | \/|  | |  \  \___|  |_\  ___/ \___ \     \   /\  |__\  \
#  |____|   |____(____  / ____|\___  >__|  |____|    (____  /__|   |__| |__|\___  >____/\___  >____  >     \_/  \_____  /
#                     \/\/         \/                     \/                    \/          \/     \/                 \/ 

# ==================================================== #
#                PlayerParticles Config                #
#               Welcome to the beginning               #
# ==================================================== #

# This value is the version of the plugin that last modified the config file
# Changing this value manually will likely result in data loss and errors!
# Do not change this manually unless specifically told to by the plugin author
version: 6.2

# Check for new versions of the plugin
# Default: true
check-updates: true

# The .lang file to use in the ./lang/ folder
# Default: 'default.lang'
lang-file: 'default.lang'

# If you're using other plugins to execute commands you may wish to turn off messages
# Default: true
messages-enabled: true

# Whether or not to use the message-prefix field when displaying messages
# Default: true
use-message-prefix: true

# The prefix to use for all PlayerParticles messages
# This is useless if use-message-prefix is set to false
# Default: '&7[&3PlayerParticles&7]'
message-prefix: '&7[&3PlayerParticles&7]'

# If the command /pp gui is enabled
# Disable this if you have your own custom GUI through another plugin
# Default: true
gui-enabled: true

# If true, styles will not display while the player is moving
# They will instead have the effect displayed at their feet
# Note: Not all styles abide by this rule, but most will
# Default: false
toggle-on-move: false

# The worlds which this plugin is disabled in
# Remove the [] before you enter world names
# Default: []
disabled-worlds: []
#  - your_world_name_here
#  - add_more_under_these

# The maximum number of particles a player can apply at once
# The GUI will only display up to 21, don't set this any higher than that
# Default: 3
max-particles: 3

# The maximum number of groups a player can have saved
# The GUI will only display up to 21, don't set this any higher than that
# Default: 10
max-groups: 10

# Max fixed effects per player
# Default: 5
max-fixed-effects: 5

# Max fixed effect creation distance
# Determines how far away a player may create a fixed effect from themselves
# This measurement is in blocks
# Set to 0 for infinite distance
# Default: 32
max-fixed-effect-creation-distance: 32

# How many ticks to wait before spawning more particles
# Increasing this value may cause less lag (if there was any), but will decrease prettiness
# Only use whole numbers greater than or equal to 1
# Going over 3 will likely look terrible
# Default: 1
ticks-per-particle: 1

# From how many blocks away should a player be able to see the particles from another player?
# Default: 48
particle-render-range-player: 48

# From how many blocks away should a player be able to see the particles from a fixed effect?
# Default: 192
particle-render-range-fixed-effect: 192

# How many out of 360 hue ticks to move per game tick
# Higher values make the rainbow cycle faster
# Note: Must be positive whole numbers
# Default: 2
rainbow-cycle-speed: 2

# ================================================================ #
#                     DATABASE CONFIGURATION                       #
# Information:                                                     #
# * This is meant for people who have multiple servers connected   #
#   together through BungeeCord. Unless you have multiple servers, #
#   it is recommended to keep the database storage disabled for    #
#   the best performance!                                          #
# ================================================================ #

# Enable Database
# Default: false
database-enable: false

# ------------------------------------------------------------------- #
# The following are only required if database-enable is set to 'true' #
# ------------------------------------------------------------------- #

# Database Hostname
# Default: ''
database-hostname: ''

# Database Port
# Default: 3306
database-port: 3306

# Database Name
# Default: ''
database-name: ''

# Database User Name
# Default: ''
database-user-name: ''

# Database User Password
# Default: ''
database-user-password: ''

# =================================================================== #
#                        GUI ICON SETTINGS                            #
# This configuration option allows you to change any of the GUI       #
# icons to whatever block/item you want.                              #
#                                                                     #
# Important Notes:                                                    #
# * If any of the block/item names are invalid the icon in the GUI    #
#   will be the barrier icon to show that it failed to load.          #
# * Do NOT change the particle/style name                             #
# * You MUST use the Spigot-given name for it to work. You can see    #
#   all the Spigot-given names at the link below:                     #
#   https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html #
# * If two icons are listed, the second one is used for below MC 1.13 #
# =================================================================== #

gui-icon:
  misc:
    particles:
      - BLAZE_POWDER
    groups:
      - CHEST
    preset_groups:
      - ENDER_CHEST
    back:
      - ARROW
    create:
      - WRITABLE_BOOK
      - BOOK_AND_QUILL
    edit_effect:
      - FIREWORK_ROCKET
      - FIREWORK
    edit_style:
      - NETHER_STAR
    edit_data:
      - BOOK
    randomize:
      - HOPPER
    reset:
      - BARRIER
  effect:
    ambient_entity_effect:
      - BEACON
    angry_villager:
      - IRON_DOOR
    barrier:
      - BARRIER
    block:
      - STONE
    bubble:
      - BUBBLE_CORAL
      - GLASS
    bubble_column_up:
      - MAGMA_BLOCK
    bubble_pop:
      - BUBBLE_CORAL_FAN
    cloud:
      - WHITE_WOOL
      - WOOL
    crit:
      - IRON_SWORD
    current_down:
      - SOUL_SAND
    damage_indicator:
      - BOW
    dolphin:
      - DOLPHIN_SPAWN_EGG
    dragon_breath:
      - DRAGON_BREATH
      - DRAGONS_BREATH
    dripping_lava:
      - LAVA_BUCKET
    dripping_water:
      - WATER_BUCKET
    dust:
      - REDSTONE
    enchant:
      - ENCHANTING_TABLE
      - ENCHANTMENT_TABLE
    enchanted_hit:
      - DIAMOND_SWORD
    end_rod:
      - END_ROD
    entity_effect:
      - GLOWSTONE_DUST
    explosion:
      - FIRE_CHARGE
      - FIREBALL
    explosion_emitter:
      - TNT
    falling_dust:
      - SAND
    firework:
      - FIREWORK_ROCKET
      - FIREWORK
    fishing:
      - FISHING_ROD
    flame:
      - BLAZE_POWDER
    footstep:
      - GRASS
    happy_villager:
      - DARK_OAK_DOOR
      - WOOD_DOOR
    heart:
      - POPPY
      - RED_ROSE
    instant_effect:
      - SPLASH_POTION
      - POTION
    item:
      - ITEM_FRAME
    item_slime:
      - SLIME_BALL
    item_snowball:
      - SNOWBALL
    large_smoke:
      - COBWEB
      - WEB
    lava:
      - MAGMA_CREAM
    mycelium:
      - MYCELIUM
      - MYCEL
    nautilus:
      - HEART_OF_THE_SEA
    note:
      - NOTE_BLOCK
    poof:
      - FIREWORK_STAR
      - FIREWORK_CHARGE
    portal:
      - OBSIDIAN
    rain:
      - PUFFERFISH_BUCKET
      - LAPIS_BLOCK
    smoke:
      - TORCH
    spell:
      - POTION
      - GLASS_BOTTLE
    spit:
      - LLAMA_SPAWN_EGG
      - PUMPKIN_SEEDS
    splash:
      - SALMON
      - FISH
    squid_ink:
      - INK_SAC
    sweep_attack:
      - GOLDEN_SWORD
      - GOLD_SWORD
    totem_of_undying:
      - TOTEM
    underwater:
      - TURTLE_HELMET
    witch:
      - CAULDRON
  style:
    arrows:
      - BOW
    batman:
      - BAT_SPAWN_EGG
      - COAL
    beam:
      - POWERED_RAIL
    blockbreak:
      - IRON_PICKAXE
    blockplace:
      - OAK_PLANKS
      - WOOD
    celebration:
      - FIREWORK_ROCKET
      - FIREWORK
    chains:
      - TRIPWIRE_HOOK
    companion:
      - NAME_TAG
    cube:
      - STONE
    feet:
      - GRASS
    halo:
      - END_PORTAL_FRAME
      - ENDER_PORTAL_FRAME
    hurt:
      - CACTUS
    invocation:
      - ENDER_EYE
      - EYE_OF_ENDER
    move:
      - PISTON
      - PISTON_BASE
    normal:
      - DIRT
    orbit:
      - ENCHANTING_TABLE
      - ENCHANTMENT_TABLE
    overhead:
      - GLOWSTONE
    point:
      - STONE_BUTTON
    quadhelix:
      - NAUTILUS_SHELL
      - ACTIVATOR_RAIL
    rings:
      - STRING
    sphere:
      - HEART_OF_THE_SEA
      - SNOWBALL
    spin:
      - BEACON
    spiral:
      - HOPPER
    swords:
      - IRON_SWORD
    thick:
      - COBWEB
      - WEB
    vortex:
      - GLOWSTONE_DUST
    wings:
      - ELYTRA

# That's everything! You reached the end of the configuration.
# Enjoy the plugin!
